version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: logs/__main__.log
    mode: a

loggers:
  sampleLogger:
    level: DEBUG
    handlers: [file]
    propagate: no

root:
  level: DEBUG
  handlers: [file]